### ISSUE TITLE
Select does not use value of option

### ISSUE THREAD

**Issue by eidmanna** [hperrin/svelte-material-ui#107]
Hi,

thank you for your amazing work. 

After npm update I had the following defect:

With this versions:
"@smui/select": {
"version": "1.0.0-beta.20",
"svelte": {
"version": "3.18.1",

not the value of Option is used by bind:value of Select, but the text of the Option:

    <Select bind:value={selectedmember}>
      <Option value="" disabled selected="selected">Your name</Option>
      {#if members}
        {#each members as member}
          <Option value={member.ShortName}>
            {member.VName} {member.FName} ({member.ShortName})
          </Option>
        {/each}
      {/if}
    </Select>

Also the initial selected="selected" of Option does not work. Instead the first not disabled Option is selected initially.

With the old versions:
 
"@smui/select": {
      "version": "1.0.0-beta.19",
"svelte": {
      "version": "3.16.7",,

everything was fine.

Thx

**Comment by eidmanna** [comment]
Here is a simple complete sample. 

Native HTML is working. MDC Select is not working.

Versions:

 "@material/select": {
      "version": "3.2.0",

"svelte": {
      "version": "3.18.1",


`<script>
  import Select, { Option } from "@smui/select";

  // let fruits = ['Apple', 'Orange', 'Banana', 'Mango'];
  let fruits = [
    { value: "a", label: "Apple" },
    { value: "o", label: "Orange" },
    { value: "b", label: "Banana" },
    { value: "m", label: "Mango" }
  ];

  let fruitChoice = fruits[1];
  let fruitChoice1 = fruits[1];

</script>

<h2>MDC Select:</h2>

<Select bind:value={fruitChoice} >
  <Option value="" />
  {#each fruits as fruit}
    <Option value={fruit} selected={fruitChoice.value === fruit.value}>{fruit.label}</Option>
  {/each}
</Select>
<p>Selected value: {fruitChoice.value}</p>
<p>Selected label: {fruitChoice.label}</p>


<h2>Native HTML:</h2>

<select bind:value={fruitChoice1} >
  <option value="" />
  {#each fruits as fruit}
    <option value={fruit} selected={fruitChoice1.value === fruit.value}>{fruit.label}</option>
  {/each}
</select>
<p>Selected value: {fruitChoice1.value}</p>
<p>Selected label: {fruitChoice1.label}</p>`

**Comment by johndeighan** [comment]
Why isn't this marked as a bug? It's definitely a bug - I was just about to report it myself. When I inspect the event record, even the options themselves contain the incorrect value, though oddly, each option has a key __value containing what SHOULD be in the value key.

**Comment by mwamp** [comment]
I'm definitely having some troubles which are fixed by simply using 1.0.0-beta.19 for select.
Git history only displays package updates.
Probably something broke with the underlying WebComponent?

**Comment by s0me0ther** [comment]
This seems to be a svelte bug (?).

I can reproduce the wrong behavior with latest svelte (v3.20.1) and latest @smui/select (1.0.0-beta.21).
Correct behavior with latest @smui/select (1.0.0-beta.21) and svelte 3.16.7 (as reported from @eidmanna)

I did not dig into the svelte code to check whats the problem.

**Comment by s0me0ther** [comment]
It seems the bug was introduced with svelte 3.19.0 @ https://github.com/sveltejs/svelte/compare/v3.18.2...v3.19.0#diff-2fa5ddeb24cf213ad13b74109ec6e7bdR682

**Comment by te-hyoung** [comment]
For anyone who's struggling with this not being fixed, use the SMUI Select component, then use the regular HTML option element and it should fix the logic issues. It fixed mine, at least.
```
<Select bind:value={valuePrefilled} label="Native Input">
        <option value=""></option>
        {#each fruits as fruit}
          <option value={fruit} selected={valuePrefilled === fruit}>{fruit}</option>
        {/each}
      </Select>
```

**Comment by haleyyoung** [comment]
For anyone who's struggling with this not being fixed, use the SMUI Select component, then use the regular HTML option element and it should fix the logic issues. It fixed mine, at least.
```
<Select bind:value={valuePrefilled} label="Native Input">
        <option value=""></option>
        {#each fruits as fruit}
          <option value={fruit} selected={valuePrefilled === fruit}>{fruit}</option>
        {/each}
</Select>
```

**Comment by eidmanna** [comment]
Today I did a retest with the newest versions of svelte and Select:
"@smui/select": "^2.0.0-beta.0"
"svelte": "^3.31.1"

unfortunately Select is still broken

@haleyyoung Your proposes workaround does not work for me.

**Comment by eidmanna** [comment]
Retest with this version:

"@smui/select": "^3.0.0-beta.10",
"svelte": "^3.37.0",

unfortunately Select is still broken

**Comment by hperrin** [comment]
I'm not seeing this issue in the demo site. Can you post a REPL that reproduces it?

**Comment by hperrin** [comment]
Keep in mind, the Select in the newest version automatically adds `selected` to the right Option, so putting `selected="selected"` on the Option will do nothing.

**Comment by eidmanna** [comment]
Hi @hperrin ,
thank you for looking into this issue and you idea to create a REPL.

For whatever reason in REPL everything works fine now.

https://svelte.dev/repl/e780451fe10f4e62bde12d01c7c43e29?version=3.37.0

Also in my local workspace I can reproduce the result :-)

If you want, you could improve you demo site by using objects with keys and labels for the select ... like in the REPL.
I think this should be the way to use select ... especially in case you want to support multi-language.  In your simple example the label is also the value of the select.

Thank you for your great work ... I especially like the use of the 'Advanced Approach'  for the integration. 
Best regards

**Comment by hperrin** [comment]
That's a good idea. I'll add an example for using objects. :)

**Comment by hperrin** [comment]
I figured out how to use objects as values. But, you'll have to provide a `key` prop to Select that returns a unique key for each object (since MDC-Web requires strings).

**Comment by hperrin** [comment]
Fixed! Verson 3.0.0-beta.12 has better support for object options. And there's a demo here:
https://sveltematerialui.com/demo/select/

**Comment by LionOnTheWeb** [comment]
Ok, I'm a bit perplexed here as to how this works with asynchronous data. For example if you want to fetch a list of countries and add each country as an option, that's easily done like so:

```javascript
<script>
    let fetchCountries = async () => {
        ...
    }

    // Create promise for country data
    let countryData = fetchCountries();
</script>
```

```html
 ...
<Select bind:value={country} label="Select your country">
    {#await countryData}
        loading countries...
        {:then countries}
            {#each countries as country}
            <Option value={country}>{country}</Option>
            {/each}
    {/await}
</Select>
```

However, I run into an issue if I want to have a country selected after the data is fetched... 
Let's assume I have another promise to fetch our current location by country

```html
 ...
<Select bind:value={country} label="Select your country">
    {#await countryData}
        loading countries...
        {:then countries}
	{#await currentLocationData}
		...loading location
		{:then location}
                     {#each countries as country}
                     <Option value="{country}" selected={location?.country==country}>{country}</Option>
	             {/each}
          {/await}
    {/await}
</Select>
```

The select options are generated but we still don't have an option selected when we get the data.
None of the examples in the demo have a pre-selected value. How do we accomplish this with smui?
