### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ok-AK** [hperrin/svelte-material-ui#163]
Hello,
Are there plans to add Typescript support to this library? Looks great and love the library!

**Comment by raphtlw** [comment]
++

**Comment by csaltos** [comment]
Now Svelte supports TypeScript directly, please check out this post as a reference -> https://svelte.dev/blog/svelte-and-typescript

**Comment by EduardsE** [comment]
Does anybody have an instruction on how to get this to work with TypeScript?

**Comment by ok-AK** [comment]
> Does anybody have an instruction on how to get this to work with TypeScript?

Svelte Material UI currently does not have typescript types defined. You can still use this lib in your typescript project and create your own typescript components that consume this lib but Svelte Material UI components will remain untyped as you do so.

**Comment by EduardsE** [comment]
> Svelte Material UI currently does not have typescript types defined. You can still use this lib in your typescript project and create your own typescript components that consume this lib but Svelte Material UI components will remain untyped as you do so.

It does compile, but I'm having difficulty configuring it in VSCode.
I keep doing this for every component and I'd rather not:
![image](https://user-images.githubusercontent.com/7456530/95671869-3fed7200-0ba4-11eb-9982-f60de408fcb4.png)

**Comment by chalkplum** [comment]
yeah i've stopped using it, why not create @types

**Comment by maranmaran** [comment]
any update on types?

**Comment by hperrin** [comment]
The current plan is to work on migrating to Typescript as the next major feature. It will take a lot of work, though.

**Comment by korompaiistvan** [comment]
hi @hperrin, I love the project it has helped me a lot to dip my toes into Svelte :)
I just found this project and it might help you create ts definitions https://github.com/IBM/sveld

**Comment by hperrin** [comment]
Thank you. That does look promising.

**Comment by hperrin** [comment]
I've been using SMUI in a TypeScript project recently, and it reeeeeeeeally makes me want to spend a weekend translating this to TypeScript.

**Comment by hperrin** [comment]
Oooooooooooooooof:
https://github.com/sciactive/nymphjs/tree/1c51dd52768b14f6f6674f6d06001c883b46ef51/packages/tilmeld-setup/app/types

**Comment by hperrin** [comment]
YO!!!! https://github.com/hperrin/svelte-material-ui/commit/cf9c6af17c59afc433c58245cc9444aece2195cc

**Comment by hperrin** [comment]
It seems like it's working!

**Comment by hperrin** [comment]
Based on how long it took to translate just that (very simple) component, "a weekend" was a very optimistic time frame.

**Comment by hperrin** [comment]
You can follow along with my progress here:
https://github.com/hperrin/svelte-material-ui/commits/typescript

**Comment by hperrin** [comment]
Better yet, you can follow my progress in the newly created project:
https://github.com/hperrin/svelte-material-ui/projects/1

**Comment by hperrin** [comment]
Closed with 331afa58f74a7552b154de35c7356a608af9e3ed! Fully typed SMUI!!!

**Comment by marekdedic** [comment]
Hi, great to hear that! Could you please add some more detail about setting up `svelte-preprocess` to the docs? I'm currently getting

```
Message:
    Module parse failed: Unexpected token (2:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import Button from './Button.svelte';
> import type { ButtonComponentDev } from './Button.types';
| export * from './Button.types';
```
and I am not really sure about the issue as I already have `svelte-preprocess` configured and use TypeScript in the project...

Thnaks!

**Comment by hperrin** [comment]
@marekdedic Can you try with the latest beta? I fixed some type issues with the ".0" beta, so the ".1" beta might help.

**Comment by marekdedic** [comment]
@hperrin It's still the same. I think it's probably just that my webpack config isn't 100% correct (but it works for my TS code), so better docs would be the way to go...

**Comment by hperrin** [comment]
I just tested it in Webpack myself, and I'm getting the same issue...

**Comment by roociferSonOfTheMorning** [comment]
I'm also having similar issues. I am using [](https://github.com/bchurlinov/svelte-typescript), running the setup typescript step and then installing the smui button.

it fails to compile: 
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@smui/common/smui.d.ts (5:7)

**Comment by hperrin** [comment]
I've fixed most of the issue... I've got one more beta to publish that I think will fix the last parts.

**Comment by hperrin** [comment]
It worked! Typed SMUI works in Webpack now!

**Comment by marekdedic** [comment]
Thanks! Unfortunately, I'm getting a different error now :/

`Module not found: Error: Can't resolve '../_index.scss' in '/home/user/project/node_modules/@smui/button'`

**Comment by hperrin** [comment]
This should also be fixed now. :)
